services:
  account_database:
    image: postgres
    networks:
      - microservices-dotnet
      
  transaction_database:
    image: mongo
    networks:
      - microservices-dotnet
  
  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Account/Account.API/Dockerfile
    networks:
      - microservices-dotnet
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - microservices-dotnet
  
  transaction.api:
    image: ${DOCKER_REGISTRY-}transactionapi
    build:
      context: .
      dockerfile: Services/Transaction/Transaction.API/Dockerfile
    networks:
      - microservices-dotnet

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - microservices-dotnet
      
  mongo-express:
    image: mongo-express
    networks:
      - microservices-dotnet
  
  portainer:
    image: portainer/portainer-ce
    networks:
      - microservices-dotnet

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

networks:
  microservices-dotnet: