version: '3.4'

x-db-env: &db-env
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: _postgresql_po&LFXlqeyBA

services:
  account_database:
    container_name: account_database
    environment:
      <<: *db-env
      POSTGRES_DB: account_database_UWb#+s1
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  account.api:
    container_name: account.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=account_database;Port=5432;Database=account_database_UWb#+s1;User Id=admin;Password=_start_Z7+4b+G2k+LZ%_end_;"
    depends_on:
      - account_database
      - rabbitmq
    ports:
      - "8001:8080"
 
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin@gmail.com
      RABBITMQ_DEFAULT_PASS: _rabbitmq_3gVE_0c!BbUby+

  pgadmin:
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: _pgadmin_v-r6yVMv5G30V#2
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
