name: Account API tests

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'  # Specify the .NET version you are using

      - name: Restore dependencies
        run: dotnet restore ./src/Services/Account/Account.Test/Account.Test.csproj

      - name: Run tests
        run: dotnet test ./src/Services/Account/Account.Test/Account.Test.csproj --no-build --verbosity normal
